added initial dispenser subsystem
Spikes-2212-Programming-Guild/RapidReact2022 pull request #13
Opened 2022-01-24 15:15 UTC by yutytuty

2022-01-26 16:07 UTC, tal-sitton requested changes

2022-01-26 16:07 UTC, tal-sitton commented on src/main/java/frc/robot/Subsystems/Dispenser.java
> +    public static Dispenser getInstance() {
not the right place for the `getInstance()` function

2022-01-26 16:07 UTC, tal-sitton commented on src/main/java/frc/robot/Subsystems/Dispenser.java
> +    private WPI_TalonSRX talon;
why are you saving this vatiable?

2022-01-26 16:07 UTC, tal-sitton commented on src/main/java/frc/robot/Subsystems/Dispenser.java
> +    }
add configureDashboard()

2022-01-26 17:34 UTC, tal-sitton requested changes

2022-01-26 17:34 UTC, tal-sitton commented on src/main/java/frc/robot/Subsystems/Dispenser.java
> +    private static final double DISTANCE_PER_PULSE = 20.32 / 4096.0;
WHY?

2022-01-26 17:34 UTC, tal-sitton commented on src/main/java/frc/robot/Subsystems/Dispenser.java
> +        rootNamespace.putNumber("encoder distance", encoder::getDistance);
WHY?

2022-01-26 17:42 UTC, tal-sitton requested changes

2022-01-26 17:42 UTC, tal-sitton commented on src/main/java/frc/robot/Subsystems/Dispenser.java
> +
add Limelight

2022-01-26 18:41 UTC, tal-sitton requested changes

2022-01-26 18:41 UTC, tal-sitton commented on src/main/java/frc/robot/Subsystems/Dispenser.java
> +public class Dispenser extends MotoredGenericSubsystem {
add docs

2022-01-26 18:57 UTC, tal-sitton requested changes

2022-01-26 18:57 UTC, tal-sitton commented on src/main/java/frc/robot/Subsystems/Dispenser.java
> + * drops cargo pieces fed to the dispenser from the transfer system into the lower hub.
rewrite

2022-01-26 19:04 UTC, tal-sitton requested changes

2022-01-26 19:04 UTC, tal-sitton commented on src/main/java/frc/robot/Subsystems/Dispenser.java
> + * drops cargo into the lower hub
that describes the command, not the subsystem

2022-01-27 15:23 UTC, yutytuty commented
removed subsystem. Deleting.

2022-01-27 15:23 UTC, closed without merging