created climb method
Spikes-2212-Programming-Guild/RapidReact2022 pull request #20
Opened 2022-01-30 18:17 UTC by OfriRosenbaum

2022-02-01 15:23 UTC, tal-sitton requested changes

2022-02-01 15:23 UTC, tal-sitton commented on src/main/java/frc/robot/Commands/Climb.java
> +        addRequirements(climberWinch, climberPlacer);
why?

2022-02-01 15:23 UTC, tal-sitton commented on src/main/java/frc/robot/Commands/Climb.java
> +        ClimberPlacer climberPlacer = ClimberPlacer.getInstance();
remove

2022-02-01 15:23 UTC, tal-sitton commented on src/main/java/frc/robot/Subsystems/ClimberPlacer.java
> +package frc.robot.Subsystems;
remove

2022-02-01 15:23 UTC, tal-sitton commented on src/main/java/frc/robot/Subsystems/ClimberWinch.java
> +    private Supplier<Double> DOWN_SPEED = rootNamespace.addConstantDouble("down speed", -0.4);
0.4 is wayyyy too much

2022-02-01 17:04 UTC, Yoel-Perman-Brilliant reviewed
I'm so sorry

2022-02-01 17:04 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/Subsystems/ClimberWinch.java
> +    private Supplier<Double> UP_SPEED = rootNamespace.addConstantDouble("up speed", 0.6);
UP_SPEED, DOWN_SPEED, HOOKED_DOWN_SPEED can all be made public and final, which makes their respective getters redundant

There's a good chance I have no idea what I'm talking about though

2022-02-02 19:08 UTC, tal-sitton requested changes

2022-02-02 19:08 UTC, tal-sitton commented on src/main/java/frc/robot/Commands/Climb.java
> +                new MoveGenericSubsystem(climberWinch, climberWinch.getUpSpeed()),
this won't work, like, physically.
you need to move closer to the bar after you open the telescopic arm for this system to catch it.

2022-02-03 15:20 UTC, tal-sitton approved these changes

2022-02-03 15:42 UTC, tal-sitton approved these changes

2022-02-03 16:08 UTC, merged