split ClimberPlacer into two instances
Spikes-2212-Programming-Guild/RapidReact2022 pull request #24
Opened 2022-02-02 18:09 UTC by yutytuty

2022-02-03 21:38 UTC, tal-sitton requested changes

2022-02-03 21:38 UTC, tal-sitton commented on src/main/java/frc/robot/Subsystems/ClimberPlacer.java
> +        else if (passedFirstStall && placer.getStatorCurrent() >= STALL_CURRENT.get())
remove the =

2022-02-05 09:37 UTC, omri00 requested changes

2022-02-05 09:37 UTC, omri00 commented on src/main/java/frc/robot/Subsystems/ClimberPlacer.java
> +        if (!passedFirstStall && placer.getStatorCurrent() > STALL_CURRENT.get())
Move `placer.getStatorCurrent() > STALL_CURRENT.get()` to seperated function for readability

2022-02-05 09:38 UTC, omri00 commented
What about commands?

2022-02-06 16:09 UTC, tal-sitton requested changes
use time instead of all of those `passedFirstStalll` things

2022-02-07 06:41 UTC, tal-sitton requested changes

2022-02-07 06:41 UTC, tal-sitton commented on src/main/java/frc/robot/Subsystems/ClimberPlacer.java
> +        this.startTime = Timer.getFPGATimestamp();
the creation of the subsystem isn't the start of the command, those are 2 separate things

2022-02-07 07:57 UTC, omri00 requested changes

2022-02-07 07:57 UTC, omri00 commented on src/main/java/frc/robot/Subsystems/ClimberPlacer.java
> +            if (currentTime - startTime > 1) {
Make this a const.

2022-02-07 07:57 UTC, omri00 commented on src/main/java/frc/robot/Subsystems/ClimberPlacer.java
> +            if (currentTime - startTime > 1) {
Do you update the current time?

2022-02-07 07:57 UTC, omri00 commented on src/main/java/frc/robot/Subsystems/ClimberPlacer.java
> +        if (isStalling()) {
Think about moving this logic to `isStalling`

2022-02-07 13:14 UTC, OfriRosenbaum requested changes

2022-02-07 13:14 UTC, OfriRosenbaum commented on src/main/java/frc/robot/Subsystems/ClimberPlacer.java
> +        super(MIN_SPEED, MAX_SPEED, "right climber placer", placer);
right???

2022-02-07 13:14 UTC, OfriRosenbaum commented on src/main/java/frc/robot/Subsystems/ClimberPlacer.java
>          this.frontLimit = new DigitalInput(RobotMap.DIO.PLACER_LIMIT_FRONT);
this will be the same limit for both instances

2022-02-07 13:14 UTC, OfriRosenbaum commented on src/main/java/frc/robot/Subsystems/ClimberPlacer.java
>          this.backLimit = new DigitalInput(RobotMap.DIO.PLACER_LIMIT_BACK);
ditto

2022-02-07 16:47 UTC, OfriRosenbaum requested changes

2022-02-07 16:47 UTC, OfriRosenbaum commented on src/main/java/frc/robot/Subsystems/ClimberPlacer.java
> +import frc.robot.Robot;
why import?

2022-02-07 17:56 UTC, tal-sitton commented
your code cant be compiled

2022-02-07 19:00 UTC, tal-sitton requested changes

2022-02-07 19:00 UTC, tal-sitton commented on src/main/java/frc/robot/Subsystems/ClimberPlacer.java
where `canMove()`?

2022-02-07 19:25 UTC, OfriRosenbaum requested changes

2022-02-07 19:39 UTC, yutytuty commented on src/main/java/frc/robot/Subsystems/ClimberPlacer.java
> +        return !(frontLimit.get() && speed < 0) && !(backLimit.get() && speed > 0);
no

2022-02-08 06:13 UTC, tal-sitton requested changes

2022-02-08 06:13 UTC, tal-sitton commented on src/main/java/frc/robot/RobotMap.java
> +        int PLACER_LEFT_LIMIT_FRONT = -1;
what placer? climber placer? intake placer?
rename

2022-02-08 06:13 UTC, tal-sitton commented on src/main/java/frc/robot/RobotMap.java
> +        int PLACER_LEFT_LIMIT_BACK = -1;
ditto

2022-02-08 06:13 UTC, tal-sitton commented on src/main/java/frc/robot/RobotMap.java
> +        int PLACER_RIGHT_LIMIT_FRONT = -1;
ditto

2022-02-08 06:13 UTC, tal-sitton commented on src/main/java/frc/robot/RobotMap.java
> +        int PLACER_RIGHT_LIMIT_BACK = -1;
ditto

2022-02-08 06:13 UTC, tal-sitton commented on src/main/java/frc/robot/Subsystems/ClimberPlacer.java
> +        return !(frontLimit.get() && speed < 0) && !(backLimit.get() && speed > 0);
why `&&`??? that's never gonna happen

2022-02-08 06:13 UTC, tal-sitton commented on src/main/java/frc/robot/Subsystems/ClimberPlacer.java
> +        return !(frontLimit.get() && speed < 0) && !(backLimit.get() && speed > 0);
the subsystem cant move when hooked

2022-02-09 15:54 UTC, Yoel-Perman-Brilliant reviewed
Your code was good so I had to nitpick

2022-02-09 15:54 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/Subsystems/ClimberPlacer.java
> +    private static ClimberPlacer rightInstance, leftInstance;
Put leftInstance first (convention A.III.b.1)

2022-02-09 15:54 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/Subsystems/ClimberPlacer.java
> +    public static ClimberPlacer getRightInstance() {
switch the order of getLeftInstance() and getRightInstance() (Convention A.III.b.1)

2022-02-09 15:54 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/Subsystems/ClimberPlacer.java
> +    private ClimberPlacer(WPI_TalonSRX placer, String side, int frontLimitPort, int backLimitPort) {
Constructor goes above getLeftInstance() and getRightInstance() (convention A.III.a.3)

2022-02-09 15:54 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/Subsystems/ClimberWinch.java
For some reason Github doesn't let me comment this above line 34, but instances should be below fields (RapidReact2022 convention Code Conventions/1)

Also add a semicolon after the last Level constant (convention A.IV.a.6)

2022-02-09 15:54 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/Subsystems/ClimberWinch.java
>      public static ClimberWinch getInstance() {
Constructor goes above getInstance() (convention A.III.a.3)

2022-02-12 11:34 UTC, OfriRosenbaum submitted a review, later dismissed

2022-02-12 11:59 UTC, tal-sitton requested changes
add to `Robot.java`

2022-02-12 14:24 UTC, tal-sitton requested changes

2022-02-12 14:24 UTC, tal-sitton commented on src/main/java/frc/robot/Robot.java
> +    ClimberPlacer leftClimberPlacer, rightClimberPlacer;
private

2022-02-12 14:24 UTC, tal-sitton commented on src/main/java/frc/robot/Robot.java
> +    ClimberWinch climberWinch;
private

2022-02-12 14:54 UTC, tal-sitton approved these changes

2022-02-12 17:49 UTC, tal-sitton approved these changes

2022-02-12 18:46 UTC, merged