Dev
Spikes-2212-Programming-Guild/RapidReact2022 pull request #30
Opened 2022-02-12 17:50 UTC by tal-sitton

2022-02-13 16:34 UTC, omri00 requested changes

2022-02-13 16:34 UTC, omri00 commented on src/main/java/frc/robot/Robot.java
> +        rootNamespace.putData("test intake", new ParallelCommandGroup(
Test code shouldn't be in dev

2022-02-13 16:34 UTC, omri00 commented on src/main/java/frc/robot/Subsystems/Transfer.java
> +    public static final double SPEED = -0.3;
Make supplier

2022-02-15 22:16 UTC, omri00 commented on src/main/java/frc/robot/Subsystems/IntakePlacer.java
> +    public static final double MAX_SPEED = 0.5;
True for all subsystems:
If this is a hard mechanical limit on the motor, like giving 0.6 for 755 motors this is ok. If however this is just the speed for the commands this should be in the dashboard so you can change it at will if you see it's moving too slow or fast

2022-02-18 16:40 UTC, omri00 requested changes

2022-02-18 16:40 UTC, omri00 commented on src/main/java/frc/robot/Subsystems/IntakeToTransfer.java
> +    private IntakeToTransfer(WPI_VictorSPX victor) {
Do you need this to be a victor? If they change it to talon why change this in 2 places? 
True for all subsystems

2022-09-08 16:16 UTC, OfriRosenbaum approved these changes

2022-09-08 16:19 UTC, OfriRosenbaum approved these changes

2022-09-08 16:21 UTC, merged