initial commit
Spikes-2212-Programming-Guild/RapidReact2022 pull request #40
Opened 2022-02-18 12:00 UTC by yutytuty

2022-02-18 12:20 UTC, tal-sitton requested changes

2022-02-18 12:20 UTC, tal-sitton commented on src/main/java/frc/robot/Robot.java
> +        rootNamespace.putData("drive forward", new DriveArcade(drivetrain, 0.5, 0));
remove

2022-02-18 12:20 UTC, tal-sitton commented on src/main/java/frc/robot/Robot.java
> +        rootNamespace.putData("drive backward", new DriveArcade(drivetrain, -0.5, 0));
ditto

2022-02-18 12:20 UTC, tal-sitton commented on src/main/java/frc/robot/Robot.java
> +        rootNamespace.putNumber("left talon current", drivetrain.getLeftTalon()::getStatorCurrent);
remove

2022-02-18 12:20 UTC, tal-sitton commented on src/main/java/frc/robot/Robot.java
> +        rootNamespace.putNumber("right talon current", drivetrain.getRightTalon()::getStatorCurrent);
remove

2022-02-18 12:20 UTC, tal-sitton commented on src/main/java/frc/robot/Robot.java
> -        rootNamespace.putData("turn robot", new DriveArcade(drivetrain, () -> 0.0, turn));
add all of those

2022-02-18 12:20 UTC, tal-sitton commented on src/main/java/frc/robot/commands/DriveUntilHitHub.java
> +        rootNamespace.update();
what are you updating?

2022-02-18 12:20 UTC, tal-sitton commented on src/main/java/frc/robot/commands/DriveUntilHitHub.java
> +    private static final Supplier<Double> STALL_CURRENT = rootNamespace.addConstantDouble("stall current", 0);
add the real value to it

2022-02-18 12:20 UTC, tal-sitton commented on src/main/java/frc/robot/commands/DriveUntilHitHub.java
> +    private static final Supplier<Double> MOVEMENT_SPEED = rootNamespace.addConstantDouble("movement speed", 0);
ditto

2022-02-18 12:20 UTC, tal-sitton commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    private final Supplier<Double> kPGyro = gyroPIDNamespace.addConstantDouble("gyro kP", 0);
why 0?

2022-02-18 12:20 UTC, tal-sitton commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    private final Supplier<Double> kIGyro = gyroPIDNamespace.addConstantDouble("gyro kI", 0);
ditto

2022-02-18 12:20 UTC, tal-sitton commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    private final Supplier<Double> kDGyro = gyroPIDNamespace.addConstantDouble("gyro kD", 0);
ditto

2022-02-18 12:20 UTC, tal-sitton commented on src/main/java/frc/robot/subsystems/Drivetrain.java
>      private static final Supplier<Double> leftCorrection = corrections.addConstantDouble("left correction", 1);
ok you changed so much in this class I'm not going to even comment on everything,
just change all of these to the right things in `autonomous-testing`

2022-02-18 12:28 UTC, yutytuty commented on src/main/java/frc/robot/commands/DriveUntilHitHub.java
> +        rootNamespace.update();
The values of the namespace

2022-02-18 12:50 UTC, OfriRosenbaum requested changes

2022-02-18 12:50 UTC, OfriRosenbaum commented on src/main/java/frc/robot/Robot.java
> +import edu.wpi.first.wpilibj.Timer;
?

2022-02-18 12:50 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/Drivetrain.java
>                      new WPI_TalonSRX(RobotMap.CAN.DRIVETRAIN_LEFT_TALON_1),
you have already created this talon

2022-02-18 12:50 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/Drivetrain.java
>                              new WPI_TalonSRX(RobotMap.CAN.DRIVETRAIN_RIGHT_TALON_1),
ditto

2022-02-18 14:34 UTC, OfriRosenbaum requested changes

2022-02-18 14:34 UTC, OfriRosenbaum commented on src/main/java/frc/robot/commands/DriveUntilHitHub.java
> +    private final Drivetrain drivetrain;
you already have a protected `tankDrivetrain` in the superclass, why create another one here?

2022-02-18 15:00 UTC, tal-sitton requested changes

2022-02-18 15:00 UTC, tal-sitton commented on src/main/java/frc/robot/Robot.java
> +        Supplier<Double> turn = rootNamespace.addConstantDouble("turn value", 0.3);
put all the namespace things **after** the `setDefaultCommand`

2022-02-18 15:00 UTC, tal-sitton commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +        this.leftTalon = leftTalon;
leftTalon = pigeonTalon

2022-02-19 07:55 UTC, tal-sitton approved these changes

2022-02-19 09:06 UTC, merged