added ReleaseCargo command
Spikes-2212-Programming-Guild/RapidReact2022 pull request #6
Opened 2022-01-20 19:38 UTC by Yoel-Perman-Brilliant

2022-01-22 09:27 UTC, tal-sitton requested changes

2022-01-22 09:27 UTC, tal-sitton commented on src/main/java/frc/robot/Subsystems/Dispenser.java
> +public class Dispenser extends GenericSubsystem {
extends `MotoredGenericSubsystem`

2022-01-22 09:27 UTC, tal-sitton commented on src/main/java/frc/robot/Subsystems/Transfer.java
> +public class Transfer extends GenericSubsystem {
ditto

2022-01-22 11:07 UTC, tal-sitton requested changes

2022-01-22 11:07 UTC, tal-sitton commented on src/main/java/frc/robot/Commands/ReleaseCargo.java
> +public class ReleaseCargo extends SequentialCommandGroup {
add documentations

2022-01-22 12:00 UTC, tal-sitton requested changes

2022-01-22 14:17 UTC, tal-sitton requested changes

2022-01-22 14:17 UTC, tal-sitton commented on src/main/java/frc/robot/Commands/ReleaseCargo.java
> +                new MoveGenericSubsystem(dispenser, Dispenser.SPEED).withTimeout(Dispenser.DISPENSER_WARM_UP_TIME),
Use the Dispenser's Encoder with `MoveGenericSubsystemPIDForSpeed`

2022-01-22 14:17 UTC, tal-sitton commented on src/main/java/frc/robot/Commands/ReleaseCargo.java
> +                        new MoveGenericSubsystem(dispenser, Dispenser.SPEED),
ditto

2022-01-22 14:17 UTC, tal-sitton commented on src/main/java/frc/robot/Subsystems/Dispenser.java
> +    public static final double SPEED;
remove

2022-01-22 14:17 UTC, tal-sitton commented on src/main/java/frc/robot/Subsystems/Dispenser.java
> +    public static final double DISPENSER_WARM_UP_TIME = 3;
remove

2022-01-22 14:17 UTC, tal-sitton commented on src/main/java/frc/robot/Subsystems/Dispenser.java
> +    public static final double TRANSFER_PLUS_DISPENSE_TIME = 5;
remove

2022-01-27 15:34 UTC, closed without merging

2022-01-27 15:35 UTC, Yoel-Perman-Brilliant commented
haven't deleted the branch in case we need it in the future